require('impatient').enable_profile()
-- General
require('plugins')
require('options')
require('auto')
require('keybinds')
require('highlights')
--require('lsp')
require('blankline')
require('treesitter')
require('icons')
-- Components
require('components/topbar')
require('components/statusline')
require('components/filetree')
require('components/dashboard')
